route:
  receiver: discord
  group_by: ['alertname', 'env']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 15m

receivers:
  - name: discord
    webhook_configs:
      - url: http://discord-bridge:9094
        send_resolved: true